---
- hosts: localhost
  connection: ssh
  gather_facts: yes
  tasks:
    - name: creating a new elastic file system
      efs:
        state: present
        name: myTestEFS
    - targets:
        subnet_id: "{{ subnet_id }}"
        security_groups: "{{ sec_id }}"
        aws_access_key: "{{ aws_access_key }}"
        aws_secret_key: "{{ aws_secret_key }}"
        region: "{{ aws_region }}"
      tags: new-efs
